# Generated by Django 3.2.13 on 2022-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20221018_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
